<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'PerryRylance\\WordPress\\RestQueryMonitor\\Entry' => '/includes/class.entry.php',
                'PerryRylance\\WordPress\\RestQueryMonitor\\Monitor' => '/includes/class.monitor.php',
                'PerryRylance\\WordPress\\RestQueryMonitor\\Plugin' => '/includes/class.plugin.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . $classes[$class];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
